### ISSUE TITLE
Issue: raw resource is not used to curl github repo

### ISSUE THREAD

**Issue by cmoulliard** [dbbaskette/tas-on-kind#4]
## Issue

The command to curl the following file `use-nodeport-for-ingress.yml ` use the URL of the github resource and not the raw file.

By consequence, the syntax to fix the problem should be 
```
curl https://raw.githubusercontent.com/cloudfoundry/cf-for-k8s/ed4c9ea79025bb4767543cb013d3c854d1cd2b72/config-optional/use-nodeport-for-ingress.yml > custom-overlays/use-nodeport-for-ingress.yml
```

**Comment by dbbaskette** [comment]
Agreed.  Nodeport makes this implementation easier and they took Nodeport  default out of the code.  I quickly found the old file and just grabbed the wrong link.

**Comment by dbbaskette** [comment]
Fixing now
