### ISSUE TITLE
Buildpack deployment not working

### ISSUE THREAD

**Issue by drnic** [dbbaskette/tas-on-kind#9]
```
cf push test-node-app -p config/cf-for-k8s/tests/smoke/assets/test-node-app
```

Does this work for you? Does TAS 0.1.0 map to cf-for-k8s 0.1.0 (where I have buildpacks are working)?

**Comment by dbbaskette** [comment]
I will give it a run and let you know.  I am on the East coast, so I will test it in the AM

**Comment by dbbaskette** [comment]
I just recreated my entire environment by cutting/pasting from the readme.  That app worked fine for me.

[output.txt](https://github.com/dbbaskette/tas-on-kind/files/4529905/output.txt)
